USE DATABASE CC_QUICKSTART_CORTEX_SEARCH_DOCS;
USE SCHEMA DATA;

CREATE OR REPLACE TABLE users (
    id INTEGER AUTOINCREMENT PRIMARY KEY,
    username STRING UNIQUE NOT NULL,
    password_hash STRING NOT NULL
);